export const teathNameAndNumber = [
  // upper right
  {
    number: 1,
    name: "Wisdom Tooth (3rd Molar)",
    mod: "Upmolar",
    quadrant: "upper",
    position: "right",
  },
  {
    number: 2,
    name: "Molar (2nd Molar)",
    mod: "Upmolar",
    quadrant: "upper",
    position: "right",
  },
  {
    number: 3,
    name: "Molar (1st Molar)",
    mod: "Upmolar",
    quadrant: "upper",
    position: "right",
  },
  {
    number: 4,
    name: "First Premolar/1st Bicuspid",
    mod: "Uppremolar",
    quadrant: "upper",
    position: "right",
  },
  {
    number: 5,
    name: "Second Premolar/2nd Bicuspid",
    mod: "Uppremolar",
    quadrant: "upper",
    position: "right",
  },
  {
    number: 6,
    name: "canine",
    mod: "Upcanine",
    quadrant: "upper",
    position: "right",
  },
  {
    number: 7,
    name: "Lateral incisor (upper right)",
    mod: "Upincisor",
    quadrant: "upper",
    position: "right",
  },
  {
    number: 8,
    name: "Central incisor (upper right)",
    mod: "Upincisor",
    quadrant: "upper",
    position: "right",
  },

  //upper left

  {
    number: 9,
    name: "Central incisor (upper left)",
    mod: "Upincisor",
    quadrant: "upper",
    position: "left",
  },
  {
    number: 10,
    name: "Lateral incisor (upper left)",
    mod: "Upincisor",
    quadrant: "upper",
    position: "left",
  },
  {
    number: 11,
    name: "Canine/Cuspid",
    mod: "Upcanine",
    quadrant: "upper",
    position: "left",
  },
  {
    number: 12,
    name: "First Premolar/1st Bicuspid",
    quadrant: "upper",
    mod: "Uppremolar",
    position: "left",
  },
  {
    number: 13,
    name: "Second Premolar/2nd Bicuspid",
    mod: "Uppremolar",
    quadrant: "upper",
    position: "left",
  },
  {
    number: 14,
    name: "First Molar",
    mod: "Upmolar",
    quadrant: "upper",
    position: "left",
  },
  {
    number: 15,
    name: "Second Molar",
    mod: "Upmolar",
    quadrant: "upper",
    position: "left",
  },
  {
    number: 16,
    name: "Third Molar/ Wisdom tooth",
    mod: "Upmolar",
    quadrant: "upper",
    position: "left",
  },

  // Lower left
  {
    number: 17,
    name: "3rd Molar or wisdom tooth (lower left )",
    mod: "Lomolar",
    quadrant: "lower",
    position: "left",
  },
  {
    number: 18,
    name: "2nd Molar",
    mod: "Lomolar",
    quadrant: "lower",
    position: "left",
  },
  {
    number: 19,
    name: "1st Molar",
    mod: "Lomolar",
    quadrant: "lower",
    position: "left",
  },
  {
    number: 20,
    name: "2nd Bicuspid or 2nd premolar",
    mod: "Lopremolar",
    quadrant: "lower",
    position: "left",
  },
  {
    number: 21,
    name: "1st Bicuspid or 1st premolar",
    mod: "Lopremolar",
    quadrant: "lower",
    position: "left",
  },
  {
    number: 22,
    name: "Cuspid or canine",
    mod: "Locanine",
    quadrant: "lower",
    position: "left",
  },
  {
    number: 23,
    name: "Lateral incisor",
    mod: "Loincisor",
    quadrant: "lower",
    position: "left",
  },
  {
    number: 24,
    name: "Central incisor",
    mod: "Loincisor",
    quadrant: "lower",
    position: "left",
  },
  // Lower right
  {
    number: 25,
    name: "Central incisor",
    mod: "Loincisor",
    quadrant: "lower",
    position: "right",
  },
  {
    number: 26,
    name: "Lateral incisor",
    mod: "Loincisor",
    quadrant: "lower",
    position: "right",
  },
  {
    number: 27,
    name: "Canine/Cuspid",
    mod: "Locanine",
    quadrant: "lower",
    position: "right",
  },
  {
    number: 28,
    name: "First Premolar/1st Bicuspid",
    mod: "Lopremolar",
    quadrant: "lower",
    position: "right",
  },
  {
    number: 29,
    name: "Second Premolar/2nd Bicuspid",
    mod: "Lopremolar",
    quadrant: "lower",
    position: "right",
  },
  {
    number: 30,
    name: "First Molar",
    mod: "Lomolar",
    quadrant: "lower",
    position: "right",
  },
  {
    number: 31,
    name: "Second Molar",
    mod: "Lomolar",
    quadrant: "lower",
    position: "right",
  },
  {
    number: 32,
    name: "Third Molar/ Wisdom tooth",
    mod: "Lomolar",
    quadrant: "lower",
    position: "right",
  },
];
